# Generated by Django 4.1.7 on 2023-03-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery_rename_ad_banner_wishlist_checkout_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(choices=[('new', 'new'), ('featured', 'featured'), ('offer', 'offer'), ('', 'default')], max_length=50),
        ),
    ]
