# Generated by Django 4.1.7 on 2023-03-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(choices=[('new', 'new'), ('featured', 'featured'), ('all', 'all'), ('offer', 'offer'), ('', 'default')], max_length=50),
        ),
    ]
