# Generated by Django 4.1.7 on 2023-03-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_labels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Ads',
        ),
    ]
